# Generated by Django 4.2.7 on 2023-12-11 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'article',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'author',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'institution',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('url', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pdf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleAuthor',
            fields=[
                ('author', models.OneToOneField(db_column='author_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='articles.author')),
            ],
            options={
                'db_table': 'article_author',
                'managed': False,
            },
        ),
    ]
