# Generated by Django 4.2.7 on 2023-12-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='elasticsearch_id',
            field=models.CharField(default='empty', max_length=255),
        ),
    ]
