# Generated by Django 4.2.7 on 2023-12-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_elasticsearch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='elasticsearch_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
