# Generated by Django 4.2.7 on 2023-12-22 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_elasticsearch_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articleauthor',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='articleauthor',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articleauthor',
            name='author',
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
        migrations.DeleteModel(
            name='Pdf',
        ),
        migrations.DeleteModel(
            name='ArticleAuthor',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
