services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - ./data/elastic:/var/lib/elasticsearch/data
    ports:
      - 9200:9200
    env_file:
      - .env
  web:
    build: .
    command: bash -c "python manage.py migrate --run-syncdb && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
    env_file:
      - .env
