# Generated by Django 4.2.7 on 2023-12-08 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userAuth", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(name="user", managers=[],),
    ]
