# Generated by Django 4.2.7 on 2023-12-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userAuth", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
